[@ww.textfield labelKey="xbdd.host" name="host" required="true"  /]
[@ww.textfield labelKey="xbdd.path" name="path" required="true" /]
[@ww.textfield labelKey="xbdd.product" name="product" required="true" /]
[@ww.textfield labelKey="xbdd.version.major" name="major" required="true" /]
[@ww.textfield labelKey="xbdd.version.minor" name="minor" required="true" /]
[@ww.textfield labelKey="xbdd.version.servicepack" name="servicepack" required="true" /]
[@ww.textfield labelKey="xbdd.plug-build" name="plug-build" required="true" /]